import java.util.Scanner;

public class Driver {
	public static void main(String[] args) {
		int input = 0;
		Scanner scanner = new Scanner(System.in);
		while (input != -1) {
			System.out.println("Choose an option to test SuperArray:");
			System.out.println(" [-1] Exit");
			System.out.println(" [ 1] View documentation");
			System.out.println(" [ 2] new SuperArray()                  Constructor");
			System.out.println(" [ 3] new SuperArray(int n)             Constructor");
			System.out.println(" [ 4] new SuperArray(int n, String s)   Constructor");
			System.out.println(" [ 5] new SuperArray(String[] s)        Constructor");
			System.out.println(" [ 6] int size()                        Get size");
			System.out.println(" [ 7] int capacity()                    Get capacity");
			System.out.println(" [ 8] boolean ifEmpty()                 Check if empty");
			System.out.println(" [ 9] boolean toString()                Pretty print");
			System.out.println(" [10] boolean set(int i, String e)      Set an index to a value");
			System.out.println(" [11] boolean contains(String e)        Find element in array");
			System.out.println(" [12] int indexOf(String e)             Find element in array");
			System.out.println(" [13] int indexOf(String e, int n)      Find element in array after position");
			System.out.println(" [14] int lastIndexOf(String e)         Find last occurence of element in array");
			System.out.println(" [15] String get(int i)                 Return element at given index");
			System.out.println(" [16] void shuffle(int i)               Shuffle array using Fisher-Yates");
			System.out.println(" [17] boolean add(String e)             Add string to array");
			System.out.println(" [18] void add(int i, String e)         Add string to array in given position");
			System.out.println(" [19] String remove(int i)              Remove index from array");
			System.out.println(" [20] boolean equals(SuperArray other)  Check if 2 SuperArrays are identical");

			System.out.print(">>> ");

			String chosenItemStr = scanner.nextLine();

			try {
				input = Integer.parseInt(chosenItemStr);
				SuperArray testArray, testArray1, testArray2, testArray3, testArray4;

				switch (input) {
					case -1:
						System.exit(0);
						break;
					case 1:
						System.out.println("There isn't any");
						break;
					case 2:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray()\"");
						System.out.println("  testArray = new SuperArray();");
						testArray = new SuperArray();
						System.out.println("Checking capacity [10] and size [0] of array");
						System.out.println("  testArray.capacity();");
						System.out.println("    "+testArray.capacity());
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Success!");
						break;
					case 3:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(int 18)\"");
						System.out.println("  testArray = new SuperArray(18);");
						testArray = new SuperArray(18);
						System.out.println("Checking capacity [18] and size [0] of array");
						System.out.println("  testArray.capacity();");
						System.out.println("    "+testArray.capacity());
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Success!");
						break;
					case 4:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(int 4, String \"test\")\"");
						System.out.println("  testArray = new SuperArray(4, \"test\");");
						testArray = new SuperArray(4, "test");
						System.out.println("Checking capacity [4] and size [4] of array");
						System.out.println("  testArray.capacity();");
						System.out.println("    "+testArray.capacity());
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Checking contents of array [ test, test, test, test ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Success!");
						break;
					case 5:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Checking capacity [3] and size [3] of array");
						System.out.println("  testArray.capacity();");
						System.out.println("    "+testArray.capacity());
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Checking contents of array [ test1, test2, test3 ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Success!");
						break;
					case 6:
						System.out.println("Defining local variables \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  SuperArray testArray1, testArray2, testArray3, testArray4;");
						System.out.println("Initializing \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  testArray1 = new SuperArray();");
						testArray1 = new SuperArray();
						System.out.println("  testArray2 = new SuperArray(7);");
						testArray2 = new SuperArray(7);
						System.out.println("  testArray3 = new SuperArray(10, \"a\");");
						testArray3 = new SuperArray(10, "a");
						System.out.println("  testArray4 = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray4 = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Testing size of testArray1 [0]");
						System.out.println("  testArray1.size();");
						System.out.println("    "+testArray1.size());
						System.out.println("Testing size of testArray2 [0]");
						System.out.println("  testArray2.size();");
						System.out.println("    "+testArray2.size());
						System.out.println("Testing size of testArray3 [10]");
						System.out.println("  testArray3.size();");
						System.out.println("    "+testArray3.size());
						System.out.println("Testing size of testArray4 [3]");
						System.out.println("  testArray4.size();");
						System.out.println("    "+testArray4.size());
						System.out.println("Success!");
						break;
					case 7:
						System.out.println("Defining local variables \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  SuperArray testArray1, testArray2, testArray3, testArray4;");
						System.out.println("Initializing \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  testArray1 = new SuperArray();");
						testArray1 = new SuperArray();
						System.out.println("  testArray2 = new SuperArray(7);");
						testArray2 = new SuperArray(7);
						System.out.println("  testArray3 = new SuperArray(10, \"a\");");
						testArray3 = new SuperArray(10, "a");
						System.out.println("  testArray4 = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray4 = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Testing capacity of testArray1 [10]");
						System.out.println("  testArray1.capacity();");
						System.out.println("    "+testArray1.capacity());
						System.out.println("Testing capacity of testArray2 [7]");
						System.out.println("  testArray2.capacity();");
						System.out.println("    "+testArray2.capacity());
						System.out.println("Testing capacity of testArray3 [10]");
						System.out.println("  testArray3.capacity();");
						System.out.println("    "+testArray3.capacity());
						System.out.println("Testing capacity of testArray4 [3]");
						System.out.println("  testArray4.capacity();");
						System.out.println("    "+testArray4.capacity());
						System.out.println("Success!");
						break;
					case 8:
						System.out.println("Defining local variables \"testArray1\", \"testArray2\"");
						System.out.println("  SuperArray testArray1, testArray2;");
						System.out.println("Initializing \"testArray1\", \"testArray2\"");
						System.out.println("  testArray1 = new SuperArray();");
						testArray1 = new SuperArray();
						System.out.println("  testArray2 = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray2 = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Testing capacity of testArray1 [true]");
						System.out.println("  testArray1.isEmpty();");
						System.out.println("    "+testArray1.isEmpty());
						System.out.println("Testing if testArray2 is empty [false]");
						System.out.println("  testArray2.isEmpty();");
						System.out.println("    "+testArray2.isEmpty());
						System.out.println("Success!");
						break;
					case 9:
						System.out.println("Defining local variables \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  SuperArray testArray1, testArray2, testArray3, testArray4;");
						System.out.println("Initializing \"testArray1\", \"testArray2\", \"testArray3\", \"testArray4\"");
						System.out.println("  testArray1 = new SuperArray();");
						testArray1 = new SuperArray();
						System.out.println("  testArray2 = new SuperArray(7);");
						testArray2 = new SuperArray(7);
						System.out.println("  testArray3 = new SuperArray(10, \"a\");");
						testArray3 = new SuperArray(10, "a");
						System.out.println("  testArray4 = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray4 = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Converting testArray1 to string [ [] ]");
						System.out.println("  testArray1.toString();");
						System.out.println("    "+testArray1.toString());
						System.out.println("Converting testArray2 to string [ [] ]");
						System.out.println("  testArray2;");
						System.out.println("    "+testArray2);
						System.out.println("Converting testArray3 to string [ [ a, a, a, a, a, a, a, a, a, a ] ]");
						System.out.println("  testArray3.toString();");
						System.out.println("    "+testArray3.toString());
						System.out.println("Converting testArray4 to string [ [ test1, test2, test3 ] ]");
						System.out.println("  testArray4;");
						System.out.println("    "+testArray4);
						System.out.println("Success!");
						break;
					case 10:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(3, \"original\")\"");
						System.out.println("  testArray = new SuperArray(3, \"original\");");
						testArray = new SuperArray(3, "original");
						System.out.println("Converting initial array to string [ [ original, original, original ] ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Setting position 1 to \"new\" [true]");
						System.out.println("  testArray.set(1, \"new\");");
						System.out.println("    "+testArray.set(1, "new"));
						System.out.println("Converting new array to string [ [ original, new, original ] ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Success!");
						break;
					case 11:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"test1\", \"test2\", \"test3\"});");
						testArray = new SuperArray(new String[] {"test1", "test2", "test3"});
						System.out.println("Testing for \"test1\" in testArray [true]");
						System.out.println("  testArray.contains(\"test1\");");
						System.out.println("    "+testArray.contains("test1"));
						System.out.println("Testing for \"test4\" in testArray [false]");
						System.out.println("  testArray.contains(\"test4\");");
						System.out.println("    "+testArray.contains("test4"));
						System.out.println("Success!");
						break;
					case 12:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"});");
						testArray = new SuperArray(new String[] {"a", "b", "a", "b", "b", "c", "a", "b"});
						System.out.println("Finding first index of \"b\" in testArray [1]");
						System.out.println("  testArray.indexOf(\"b\");");
						System.out.println("    "+testArray.indexOf("b"));
						System.out.println("Success!");
						break;
					case 13:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"});");
						testArray = new SuperArray(new String[] {"a", "b", "a", "b", "b", "c", "a", "b"});
						System.out.println("Finding first index of \"b\" in testArray after index 0 [1]");
						System.out.println("  testArray.indexOf(\"b\", 0);");
						System.out.println("    "+testArray.indexOf("b", 0));
						System.out.println("Finding first index of \"b\" in testArray after index 1 [3]");
						System.out.println("  testArray.indexOf(\"b\", 1);");
						System.out.println("    "+testArray.indexOf("b", 1));
						System.out.println("Finding first index of \"b\" in testArray after index 3 [4]");
						System.out.println("  testArray.indexOf(\"b\", 3);");
						System.out.println("    "+testArray.indexOf("b", 3));
						System.out.println("Finding first index of \"b\" in testArray after index 5 [7]");
						System.out.println("  testArray.indexOf(\"b\", 5);");
						System.out.println("    "+testArray.indexOf("b", 5));
						System.out.println("Success!");
						break;
					case 14:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"});");
						testArray = new SuperArray(new String[] {"a", "b", "a", "b", "b", "c", "a", "b"});
						System.out.println("Finding last index of \"a\" in testArray [6]");
						System.out.println("  testArray.lastIndexOf(\"a\");");
						System.out.println("    "+testArray.lastIndexOf("a"));
						System.out.println("Success!");
						break;
					case 15:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"a\", \"b\", \"b\", \"c\", \"a\", \"b\"});");
						testArray = new SuperArray(new String[] {"a", "b", "a", "b", "b", "c", "a", "b"});
						System.out.println("Finding contents of index 0 [a]");
						System.out.println("  testArray.get(0);");
						System.out.println("    "+testArray.get(0));
						System.out.println("Finding contents of index 1 [b]");
						System.out.println("  testArray.get(1);");
						System.out.println("    "+testArray.get(1));
						System.out.println("Finding contents of index 2 [a]");
						System.out.println("  testArray.get(2);");
						System.out.println("    "+testArray.get(2));
						System.out.println("Finding contents of index 4 [b]");
						System.out.println("  testArray.get(4);");
						System.out.println("    "+testArray.get(4));
						System.out.println("Finding contents of index 6 [a]");
						System.out.println("  testArray.get(6);");
						System.out.println("    "+testArray.get(6));
						System.out.println("Finding contents of index 7 [b]");
						System.out.println("  testArray.get(7);");
						System.out.println("    "+testArray.get(7));
						System.out.println("Success!");
						break;
					case 16:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"});");
						testArray = new SuperArray(new String[] {"a", "b", "c", "d", "e", "f", "g", "h"});
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Shuffling array");
						System.out.println("  testArray.shuffle();");
						testArray.shuffle();
						System.out.println("Printing contents of shuffled array");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Success!");
						break;
					case 17:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"});");
						testArray = new SuperArray(new String[] {"a", "b", "c", "d", "e", "f", "g", "h"});
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [8]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Adding \"i\" to the array [true]");
						System.out.println("  testArray.add(\"i\");");
						System.out.println("    "+testArray.add("i"));
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h, i ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [9]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Adding null to the array [true]");
						System.out.println("  testArray.add(null);");
						System.out.println("    "+testArray.add(null));
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h, i, null ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [10]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Success!");
						break;
					case 18:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"d\", \"e\", \"f\", \"g\", \"h\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"d\", \"e\", \"f\", \"g\", \"h\"});");
						testArray = new SuperArray(new String[] {"a", "b", "d", "e", "f", "g", "h"});
						System.out.println("Printing contents of array [ a, b, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [7]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Adding \"c\" to the array at index 2");
						System.out.println("  testArray.add(2, \"c\");");
						testArray.add(2, "c");
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [8]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Success!");
						break;
					case 19:
						System.out.println("Defining local variable \"testArray\"");
						System.out.println("  SuperArray testArray;");
						System.out.println("Initializing \"testArray\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"})\"");
						System.out.println("  testArray = new SuperArray(new String[] {\"a\", \"b\", \"c\", \"c\", \"d\", \"e\", \"f\", \"g\", \"h\"});");
						testArray = new SuperArray(new String[] {"a", "b", "c", "c", "d", "e", "f", "g", "h"});
						System.out.println("Printing contents of array [ a, b, c, c, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [9]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Removing index 2 from the array");
						System.out.println("  testArray.remove(2);");
						System.out.println(testArray.remove(2));
						System.out.println("Printing contents of array [ a, b, c, d, e, f, g, h ]");
						System.out.println("  testArray.toString();");
						System.out.println("    "+testArray.toString());
						System.out.println("Checking size of array [8]");
						System.out.println("  testArray.size();");
						System.out.println("    "+testArray.size());
						System.out.println("Success!");
						break;
					case 20:
						System.out.println("Defining local variables \"testArray1\", \"testArray2\", \"testArray3\"");
						System.out.println("  SuperArray testArray1, testArray2, testArray3;");
						System.out.println("Initializing \"testArray1\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\"})\"");
						System.out.println("  testArray1 = new SuperArray(new String[] {\"a\", \"b\", \"c\"});");
						testArray1 = new SuperArray(new String[] {"a", "b", "c"});
						System.out.println("Initializing \"testArray2\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\"})\"");
						System.out.println("  testArray2 = new SuperArray(new String[] {\"a\", \"b\", \"c\"});");
						testArray2 = new SuperArray(new String[] {"a", "b", "c"});
						System.out.println("Initializing \"testArray3\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\"})\"");
						System.out.println("  testArray3 = new SuperArray(new String[] {\"a\", \"b\", \"c\", \"d\"});");
						testArray3 = new SuperArray(new String[] {"a", "b", "c", "d"});
						System.out.println("Initializing \"testArray3\" with constructor \"new SuperArray(new String[] {\"a\", \"b\", \"d\"})\"");
						System.out.println("  testArray3 = new SuperArray(new String[] {\"a\", \"b\", \"d\"});");
						testArray4 = new SuperArray(new String[] {"a", "b", "d"});
						System.out.println("Testing \"testArray1\" against \"testArray1\" [true]:");
						System.out.println("  testArray1.equals(testArray1)");
						System.out.println("    "+testArray1.equals(testArray1));
						System.out.println("Testing \"testArray1\" against \"testArray2\" [true]:");
						System.out.println("  testArray1.equals(testArray2)");
						System.out.println("    "+testArray1.equals(testArray2));
						System.out.println("Testing \"testArray1\" against \"testArray3\" [false]:");
						System.out.println("  testArray1.equals(testArray3)");
						System.out.println("    "+testArray1.equals(testArray3));
						System.out.println("Testing \"testArray1\" against \"testArray4\" [false]:");
						System.out.println("  testArray1.equals(testArray4)");
						System.out.println("    "+testArray1.equals(testArray4));
						break;
					default:
						System.out.println("\nInvalid value\n");
				}

				System.out.println("\n\nPress return to continue\n");
				scanner.nextLine();
			} catch (Exception e) {
				System.out.println("\nInvalid value\nPress return to continue\n");
				scanner.nextLine();
			}
		}
	}
}
